# Generated by Django 5.1.6 on 2025-03-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_compeleted',
            new_name='is_completed',
        ),
    ]
